/*
1. 멤버 이름으로 조인한다.
2. 그룹별로 이름의 개수만큼 카운한다.
3. 
*/
    # SELECT 
    # M.MEMBER_NAME, COUNT(*) AS COUT
    # FROM 
    # MEMBER_PROFILE AS M INNER JOIN REST_REVIEW AS R 
    # ON M.MEMBER_ID = R.MEMBER_ID
    # GROUP BY M.MEMBER_ID 
    # ORDER BY COUT DESC
    # LIMIT 1
    # ;
SELECT 
MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM 
MEMBER_PROFILE MP
JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC
;
